// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiycgmuccerxskllbofe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9peWNnbXVjY2VyeHNrbGxib2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwNzc0ODQsImV4cCI6MjA4NjY1MzQ4NH0.EcnhHJbKRopdjYlddmyBwwpCb-6bdNaFNaTrFYIbayo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});